name: Build and deploy an app to AKS with Helm

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

env:
  RESOURCE_GROUP: "azurehelm"
  CHART_PATH: "./istio/manifests/charts/default/"
  CHART_OVERRIDE_PATH: "./istio/manifests/charts/default/values.yaml"
  CLUSTER_NAME: "kube1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
 
    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
    - name: Get K8s context
      uses: azure/aks-set-context@v2.0
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }} 
    # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
    - name: Get K8s context
      uses: azure/aks-set-context@v2.0
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}

    # Runs Helm to create manifest files

    - name: Create KinD cluster
      uses: helm/kind-action@v1.0.0


    - name: Install Istio
      uses: ./istio/manifests/charts/default/

    - name: check Istio CRD's installed and ready
      run: |
          kubectl -n istio-system wait pods --selector=app=istio-ingressgateway --for=condition=Ready