name: Build and deploy an app to AKS with Helm

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  RESOURCE_GROUP: "azurehelm"
  CLUSTER_NAME: "kube1"
  NAMESPACE: "istio-system"

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: self-hosted
    steps:
    # Checks out the repository this file is in
    - uses: actions/checkout@v3
    
    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
    - name: Get K8s context
      uses: azure/aks-set-context@v2.0
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }} 
    # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
    - name: Get K8s context
      uses: azure/aks-set-context@v2.0
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}

    - name: create namespace
      run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -  
    - name: helm add repo
      run: |
         helm repo add istio https://istio-release.storage.googleapis.com/charts
    - name: helm update
      run: |
         helm repo update
    - name: helm install
      run: |
         helm upgrade --install istio-base --debug  istio/base  -n istio-system --wait 
